apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app-deployment
  namespace: frontend
spec:
  replicas: 2  # Number of desired replicas/pods
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
      - name: frontend
        image: gcr.io/kartik69/frontend:latest  # Replace with your actual container image
        ports:
        - containerPort: 3000  # Replace with the port your application listens on
