apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-app-deployment
  namespace: frontend
spec:
  replicas: 2  # Number of desired replicas/pods
  selector:
    matchLabels:
      app: back-app
  template:
    metadata:
      labels:
        app: back-app
    spec:
      containers:
      - name: backend
        image: gcr.io/kartik69/backend:latest  # Replace with your actual container image
        ports:
        - containerPort: 3001  # Replace with the port your application listens on
---

# https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: backend-load-balancer-service
  namespace: frontend
spec:
  selector:
    app: back-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
 
